package com.redhat.saiello.data;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _BlogPost was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BlogPost extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ID_PROPERTY = "id";
    public static final String TITLE_PROPERTY = "title";

    public static final String ID_PK_COLUMN = "ID";

    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

}
